### ISSUE TITLE
Automation triggered every time HA reboots

### ISSUE THREAD

**Issue by sfnetwork** [fireflyelectronix/wifidoorbell#3] opened 2019-03-21 13:31 UTC
In Home Assistant, the MQTT trigger works when I ring the doorbell but the only pending issue I can't resolve it that the automation gets triggered every time I reboot HA or reload automations (or turn off and ON the automation.

I took the time to set it up following your doc:
First, I setup the doorbell:
- I configured the broker, port and “ha/doorbell/notify” for the topic.

- In HA, I setup this automation
```
- id: '1552933754824'
  alias: Notification - sonnette porte
  trigger:
  - platform: mqtt
    topic: ha/doorbell/notify
  condition: []
  action:
  - data:
      message: ding dong! Ça sonne à la porte!
      title: Home Assistant - sfHome
    service: notify.pushover_sylvain
  - data:
      delay: 00:00:05
      message: Ding dong! Ça sonne à la porte!!
      sonos_entity: media_player.bureau
      volume: '0.3'
    service: script.sonos_say
```

- Following the doc, I setup the battery sensor:

```
#Doobell MQTT battery  
  - platform: mqtt
    state_topic: "ha/doorbell/notify"
    value_template: '{{value_json.batt}}'
    unit_of_measurement: "Volts"
    name: "Batterie sonnette MQTT"  
```
This works fine.

- I tried setting up a binary sensor but it just switches on / off every time it’s triggered (or rebooted), not really helpful…

```
#Sonette de porte
  - platform: mqtt
    name: Sonnette porte
    state_topic: "ha/doorbell/notify"
    value_template: "{%if is_state(entity_id,\"on\")-%}OFF{%-else-%}ON{%-endif%}"
```

I don't know how to fix this since the doorbell just send this same MQTT topic every time...
***My knowloedge in MQTT is very new and limited BTW...

**Comment by fireflyelectronix** [comment] 2019-03-23 00:15
We are looking into this. It is most likely a retain flag that is set somewhere. This means that the message is being retained and home assistant is seeing the message on restart. There is a thread here that we are checking into. https://community.home-assistant.io/t/automation-triggered-at-restart-hass/75563

**Comment by sfnetwork** [comment] 2019-03-23 12:57
ah ok, thanks... I presume this would be something to fix in a firmware update, right? Or this might be fixable from my end?
Because in the thread form your link (that I already seen before), didn't seem to end up with a solution as far as I could tell...

**Comment by sfnetwork** [comment] 2019-03-29 19:03
Any update? I saw the code was updated but unsure if it's related...

**Comment by fireflyelectronix** [comment] 2019-03-29 20:22
We believe this may be the cause. On line 55 the true flag was removed. This flag tells the MQTT broker to retain the message. When Home Assistant restarts, it sees that retained messaged and triggers off of it for the automation. 

We are testing right now to make sure that Home Assistant will still keep the battery voltage level if this flag is removed. 

https://github.com/fireflyelectronix/wifidoorbell/blob/25007619c7a8d3f6aa32647094dcd7e6e351a520/WiFi-Doorbell-DB100/WiFi-Doorbell-DB100.ino#L55

**Comment by sfnetwork** [comment] 2019-03-29 21:55
Thanks...If confirmed, how would I be able to update the firmware, will you have a procedure for this? 
I could test but no clue how to update teh doorbell...

**Comment by fireflyelectronix** [comment] 2019-04-01 13:00
Looks like we do need to publish with the retain flag in order for the sensor in Home Assistant to recall the last value. https://www.home-assistant.io/components/sensor.mqtt/

If we remove the retain flag, the battery voltage level will be unknown when home assistant restarts. It may be  that we will need to publish two different topics. One will publish battery and the other will publish for the automation.

**Comment by sfnetwork** [comment] 2019-04-03 22:37
I see there was an update to resolve this...
No clue how to update the device though, could you provide instructions?

**Comment by fireflyelectronix** [comment] 2019-04-05 18:57
we have instructions on the read.me file and will add more details to make it clear.

**Comment by fireflyelectronix** [comment] 2019-04-05 18:58
Fixed in v1.1 Release

**Closed as completed by fireflyelectronix** 2019-04-05 18:58 UTC
Labels: bug

**Comment by sfnetwork** [comment] 2019-04-05 19:20
Those instructions don't seem for the end user... I have no clue where to begin...
How do I connect the device to be able to update it? (looks like OTA is not supported yet)

I thought this was a consumer product, didn't expect this kind of procedure to resolve an issue on a device that was originally supported on HA...
I guess I should have seen this procedure before purchase and avoid buying it but I didn't expect to have to do a firmware update out of the box to use a feature HA that was supposed to be supported already...

**Comment by sfnetwork** [comment] 2019-04-05 20:01
I saw the procedure but am I expected to solder something here after I purchase a FTDI?
"Connect the FTDI to the J2 Header on the WiFi Doorbell Sensor."

**Comment by sfnetwork** [comment] 2019-04-27 16:38
I got the new device with latest firmware (and OTA update capacity)
Configured it in HA and works perfectly!
Thanks!!!
